//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Lect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Admin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Admin()
        {
            this.Candidates = new HashSet<Candidate>();
            this.Parties = new HashSet<Party>();
        }
    
      
[Display(Name = "Username")]
    public string Admin_Username { get; set; }

    [Required]
    [DataType(DataType.Password)]
    [Display(Name = "Password")]
    [StringLength(10, ErrorMessage = "The {0} must be at least {2} characters and max 10 characters long.", MinimumLength = 5)]
    public string Admin_Password { get; set; }

    [Required]
    [Display(Name = "Confirm Password")]
    [DataType(DataType.Password)]
    [Compare("Admin_Password", ErrorMessage = "The password and confirmation password do not match.")]
    public string ConfirmPassword { get; set; }

    [Required]
    [Display(Name = "Name")]
    public string Admin_Name { get; set; }

    [Display(Name = "Middle Name")]
    public string Admin_MidName { get; set; }

    [Required]
    [Display(Name = "Surname")]
    public string Admin_Surname { get; set; }

    [Required]
    [Display(Name = "Date of Birth")]
    [DataType(DataType.Date)]
    public System.DateTime Admin_DOB { get; set; }

    [Required]
    [Display(Name = "Gender")]
    public string Admin_Gender { get; set; }

    [Required]
    [Display(Name = "Email")]
    [EmailAddress]
    public string Admin_Email { get; set; }

    [Display(Name = "Recovery Question")]
    public string Admin_RecoveryQ { get; set; }

    [Display(Name = "Recovery Answer")]
    public string Admin_RecoveryA { get; set; }

    [Display(Name = "Image")]
    public byte[] Admin_Image { get; set; }

    public string Admin_ImagePath { get; set; }


    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Party> Parties { get; set; }
    }
}
