//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Lect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Votes = new HashSet<Vote>();
        }

        [Display(Name = "ID")]
        public string Candidate_ID { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Candidate_Name { get; set; }

        [Display(Name = "Middle Name")]
        public string Candidate_MidName { get; set; }

        [Required]
        [Display(Name = "Surname")]
        public string Candidate_Surname { get; set; }

        [Required]
        [Display(Name = "Student Number")]
        public int Candidate_StudentNumber { get; set; }

        [Required]
        [Display(Name = "Gender")]
        public string Candidate_Gender { get; set; }

        [Required]
        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime Candidate_DOB { get; set; }

        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Candidate_Email { get; set; }

        [Required]
        [Display(Name = "Course")]
        public string Candidate_Course { get; set; }

        [Required]
        [Display(Name = "Year of Study")]
        public int Candidate_YearOfStudy { get; set; }

        [Required]
        [Display(Name = "Campus")]
        public string Candidate_Campus { get; set; }

        [Required]
        [Display(Name = "Position")]
        public string Candidate_Position { get; set; }

        [Required]
        [Display(Name = "Status")]
        public string Candidate_Status { get; set; }

        [Display(Name = "Total Votes")]
        public Nullable<int> Candidate_TotalVotes { get; set; }

        [Required]
        [Display(Name = "Party")]
        public string Party_Name { get; set; }

        //[Required]
        [Display(Name = "Admin Incharge")]
        public string Admin_Username { get; set; }

        [Display(Name = "Image")]
        public byte[] Candidate_Image { get; set; }

        public string Candidate_ImagePath { get; set; }

        public bool isChecked { get; set; }

        public List<Candidate> cand { get; set; }

        public string GenerateCandID()
        {
            string x = Candidate_Name.Substring(0, 1);
            string y = Candidate_StudentNumber.ToString();
            string z = Candidate_Surname.Substring(0, 1);

            string cand = x + y + z;

            return cand;
        }


        public virtual Admin Admin { get; set; }
        public virtual Party Party { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
