//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Lect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MockStudent
    {
        public int Stu_Num { get; set; }
        public string Stu_Name { get; set; }
        public string Stu_Surname { get; set; }
        public string Stu_Gender { get; set; }
        public System.DateTime Stu_DOB { get; set; }
        public string Stu_Email { get; set; }
        public string Stu_Course { get; set; }
        public string Stu_Campus { get; set; }
        public int Stu_YearOfStudy { get; set; }
    }
}
