//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Lect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Party
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Party()
        {
            this.Candidates = new HashSet<Candidate>();
            this.Votes = new HashSet<Vote>();
        }

        [Required]
        [Display(Name = "Party Name")]
        public string Party_Name { get; set; }

        [Required]
        [Display(Name = "Party Description")]
        public string Party_Description { get; set; }

        [Display(Name = "Number of Candidates")]
        public Nullable<int> Party_NoOfCandidates { get; set; }

        [Required]
        [Display(Name = "Status")]
        public string Party_Status { get; set; }

        [Display(Name = "Total Votes")]
        public Nullable<int> Party_TotalVotes { get; set; }

        [Required]
        [Display(Name = "Admin Incharge")]
        public string Admin_Username { get; set; }

        [Display(Name = "Image")]
        public byte[] Party_Image { get; set; }

        public string Party_ImagePath { get; set; }




        public virtual Admin Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
