//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Lect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaveImage
    {
        public int SaveImageID { get; set; }
        public byte[] Image { get; set; }
        public string ImagePath { get; set; }
    }
}
