//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Lect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Votes = new HashSet<Vote>();
        }

        [Required]
        [Display(Name = "Student Number")]
        public int Student_Number { get; set; }

        [Required]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Student_Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Student_Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        [Required]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Student_Email { get; set; }

        [Required]
        [Display(Name = "Gender")]
        public string Student_Gender { get; set; }

        [Required]
        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        public System.DateTime Student_DOB { get; set; }

        [Required]
        [Display(Name = "Course")]
        public string Student_Course { get; set; }

        [Required]
        [Display(Name = "Year of Study")]
        public int Student_YearOfStudy { get; set; }

        [Required]
        [Display(Name = "Campus")]
        public string Student_Campus { get; set; }

        [Display(Name = "Voted")]
        public string Student_Voted { get; set; }

        [Display(Name = "Recovery Question")]
        public string Student_RecoveryQ { get; set; }

        [Display(Name = "Recovery Answer")]
        public string Student_RecoveryA { get; set; }

        [Display(Name = "Image")]
        public byte[] Student_Image { get; set; }

        public string Student_ImagePath { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
